name: "Bug 报告"
description: "报告一个可重现的缺陷或意外行为"
title: "[BUG] {{ body | split: '\n' | first | strip_html }}"
labels: ["bug"]
assignees:
  - "Hotakus"
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交 Bug 报告！请提供尽可能详细的信息。

  - type: input
    id: os-version
    attributes:
      label: "操作系统及版本"
      description: "例如: Windows 11 22H2, Ubuntu 20.04"
      placeholder: "Windows 11 22H2"
    validations:
      required: true

  - type: input
    id: soft-version
    attributes:
      label: "出现问题的软件版本"
      description: "例如: v1.0.0"
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "重现步骤"
      description: "清晰描述如何重现这个问题"
      placeholder: |
        例如：
        1. 在终端运行命令 `npm start`
        2. 访问 http://localhost:3000
        3. 点击 X 按钮
        4. 观察到 Y 现象而未出现预期的 Z 现象
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "预期行为"
      description: "描述你期望看到的结果"
      placeholder: "填写你的期望"

  - type: textarea
    id: logs
    attributes:
      label: "相关日志或输出"
      description: "如果有错误日志，请粘贴于此（使用代码块包裹）"
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: "严重程度"
      options:
        - "低 - 微小问题，不影响使用"
        - "中 - 部分功能受影响"
        - "高 - 主要功能不可用"
        - "严重 - 导致系统崩溃或数据丢失"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "确认条款"
      options:
        - label: "我已确认此问题在最新版本中仍然存在"
          required: true
        - label: "我已搜索过现有的 Issue，此问题尚未被报告"
          required: true
        - label: "我已按照格式填写标题"
          required: true
