name: "publish"

on:
  push:
    tags: ["test-v*"]
    branches:
      - release
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
#          - platform: "macos-latest"
#            args: "--target x86_64-apple-darwin"       # Intel
#          - platform: "macos-latest"
#            args: "--target aarch64-apple-darwin"     # Arm (M1/M2)

    runs-on: ${{ matrix.platform }}
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Node + pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install

      # Rust
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && matrix.args != '' && matrix.args || '' }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            src-tauri -> ../../target

      # System dependencies (Ubuntu)
      - name: Install system dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf pkg-config libudev-dev

      - name: Generate Changelog
        id: build_changelog
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          # 只生成当前版本和上一个版本之间的 changelog
          toTag: ${{ github.ref_name }}

      # Tauri build + release
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          RELEASE_BODY: ${{ env.RELEASE_BODY }}
        with:
          tagName: ${{ !github.event.pull_request.head.repo.fork && format('v{0}', env.npm_package_version) || '' }}
          releaseName: ${{ !github.event.pull_request.head.repo.fork && format('Release v{0}', env.npm_package_version) || '' }}
          releaseBody: ${{ steps.build_changelog.outputs.changelog }}
          releaseDraft: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
          prerelease: true
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          args: ${{ matrix.args }}
