name: "publish"

on:
  push:
    tags: ["test-v*"]
    branches:
      - release
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
#          - platform: "macos-latest"
#            args: "--target x86_64-apple-darwin"       # Intel
#          - platform: "macos-latest"
#            args: "--target aarch64-apple-darwin"     # Arm (M1/M2)

    runs-on: ${{ matrix.platform }}
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Node + pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install

      # Rust
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && matrix.args != '' && matrix.args || '' }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            src-tauri -> ../../target

      # System dependencies (Ubuntu)
      - name: Install system dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf pkg-config libudev-dev

      # Generate changelog for this release only
      - name: Generate changelog
        if: ${{ !github.event.pull_request.head.repo.fork }}
        shell: bash
        run: |
          npm install -g auto-changelog
          
          # 根据不同操作系统选择合适的命令语法
          case "${{ matrix.platform }}" in
            ubuntu-22.04 | macos-latest)
              # macOS 和 Linux (bash)
              PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "v0.0.0")
              echo "Previous tag: $PREV_TAG"
              npx auto-changelog --from-tag "$PREV_TAG" --to-tag HEAD --output CHANGELOG.md
              ;;
            windows-latest)
              # Windows (PowerShell)
              PREV_TAG=$(pwsh -c "git describe --tags --abbrev=0 HEAD^ 2> `$null || Write-Output \"v0.0.0\"")
              echo "Previous tag: $PREV_TAG"
              npx auto-changelog --from-tag "$PREV_TAG" --to-tag HEAD --output CHANGELOG.md
              ;;
          esac
          
          # 写入 RELEASE_BODY 环境变量
          {
            echo "RELEASE_BODY<<EOF"
            echo "See the assets to download this version and install."
            echo ""
            cat CHANGELOG.md
            echo "EOF"
          } >> "$GITHUB_ENV"

      # Tauri build + release
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          RELEASE_BODY: ${{ env.RELEASE_BODY }}
        with:
          tagName: ${{ !github.event.pull_request.head.repo.fork && format('v{0}', env.npm_package_version) || '' }}
          releaseName: ${{ !github.event.pull_request.head.repo.fork && format('Release v{0}', env.npm_package_version) || '' }}
          releaseBody: ${{ env.RELEASE_BODY }}
          releaseDraft: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
          prerelease: true
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          args: ${{ matrix.args }}
