name: PR Checks

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - uses: dtolnay/rust-toolchain@stable

      - run: cd src-tauri && cargo build --locked
