name: Tauri Cross-Platform Build and Release

on:
  push:
    tags: ["v*"]   # 匹配 v 开头的标签，如 v0.1.8
  workflow_dispatch: # 手动触发支持

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write

    steps:
      # 步骤 1: 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}

      # ✅ 关键修复：验证图标路径
      - name: Verify Icon Paths
        shell: bash
        run: |
          echo "当前工作目录: $(pwd)"
          echo "图标文件列表:"
          ls -l icons/
          
          # 确保图标路径正确
          if [ -f "icons/icon.ico" ]; then
            echo "✅ 找到 icon.ico 文件"
          else
            echo "::error::未找到 icons/icon.ico 文件！请确保图标位于项目根目录的 icons 文件夹中"
            exit 1
          fi
          
          if [ -f "icons/icon.png" ]; then
            echo "✅ 找到 icon.png 文件"
          else
            echo "::warning::未找到 icons/icon.png 文件，非Windows构建可能使用默认图标"
          fi

      # 步骤 2: 安装 Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src, clippy

      # 步骤 3: 安装 Tauri CLI
      - name: Install Tauri CLI
        run: cargo install tauri-cli --version "^2.0.0"

      # 步骤 4: 安装 Linux 依赖
      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            librsvg2-dev \
            patchelf \
            libudev-dev \
            pkg-config \
            libayatana-appindicator3-dev

      # 步骤 5: 安装 WiX 工具集
      - name: Install WiX Toolset for Windows
        if: matrix.platform == 'windows-latest'
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix.zip"
          Expand-Archive -Path "wix.zip" -DestinationPath "wix"
          $wixPath = "$pwd\wix"
          echo "WIX_PATH=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "$wixPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # 步骤 6: 检查 Windows WebView2
      - name: Check Windows Dependencies
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          $regPath = "HKLM:\SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"
          if (-not (Test-Path $regPath)) {
            Write-Host "WebView2 not found, installing..."
            $installerPath = "$env:TEMP\MicrosoftEdgeWebview2Setup.exe"
            Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile $installerPath
            Start-Process -FilePath $installerPath -ArgumentList "/silent /install" -Wait
          } else {
            Write-Host "WebView2 is already installed"
          }

      # 步骤 7: 设置版本号
      - name: Set Application Version
        shell: bash
        run: |
          BASE_VERSION=$(grep -E '"version":' tauri.conf.json | sed -E 's/.*"version": *"([^"]+).*/\1/')
          
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            VERSION="${BASE_VERSION}+manual.${{ github.run_id }}"
          fi

          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            FINAL_VERSION=$(echo "$VERSION" | sed -E 's/[-+].*//')
            FINAL_VERSION=$(echo "$FINAL_VERSION" | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')
            if [[ "$FINAL_VERSION" =~ ^[0-9]+\.[0-9]+$ ]]; then
              FINAL_VERSION="$FINAL_VERSION.0"
            elif [[ "$FINAL_VERSION" =~ ^[0-9]+$ ]]; then
              FINAL_VERSION="$FINAL_VERSION.0.0"
            fi
            echo "📦 Windows MSI version: $FINAL_VERSION"
          else
            FINAL_VERSION=$VERSION
            echo "📦 Final version: $FINAL_VERSION"
          fi

          sed -i.bak -E "s/\"version\": *\"[^\"]+\"/\"version\": \"$FINAL_VERSION\"/" tauri.conf.json && rm tauri.conf.json.bak
          sed -i.bak -E "s/^version = \"[^\"]+\"/version = \"$FINAL_VERSION\"/" Cargo.toml && rm Cargo.toml.bak
          echo "Updated tauri.conf.json version:"
          grep '"version":' tauri.conf.json
          echo "Updated Cargo.toml version:"
          grep '^version =' Cargo.toml

      # ✅ 关键修复：确保使用正确图标路径
      - name: Build Tauri Application
        shell: bash
        run: |
          # 打印当前目录结构，用于调试
          echo "构建前目录结构:"
          ls -l
          ls -l src-tauri
          
          # 在Windows上强制使用绝对路径
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            cargo tauri build --verbose --config '{"build": {"icon": ["'${{ github.workspace }}'/icons/icon.ico"]}}'
          else
            cargo tauri build --verbose
          fi

      # 步骤 9: 上传构建产物
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ github.ref_name || 'manual' }}
          path: |
            target/release/bundle/**
            target/**/*.msi
            target/**/*.AppImage
            target/**/*.deb
          retention-days: 7
          if-no-files-found: warn

      # 步骤 10: 显示构建产物信息
      - name: Show Build Results
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            dir /s /b target\\release\\bundle || true
            dir /s /b target\\*.msi || true
          else
            find target/release/bundle -type f -print || true
            find ${{ github.workspace }} -name '*.AppImage' -o -name '*.deb' -print || true
          fi

  # Release 发布任务
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: build-*
          merge-multiple: true

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "CHANGELOG.md"

      - name: Check Prerelease Status
        id: check-prerelease
        shell: bash
        run: |
          if [[ "${{ github.ref_name }}" =~ -[a-zA-Z0-9] ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ fromJson(steps.check-prerelease.outputs.prerelease) }}
          files: artifacts/**/*
          draft: false
          generate_release_notes: false

      - name: Show Release URL
        shell: bash
        run: echo "Release created at ${{ steps.create-release.outputs.url }}"