name: Tauri Cross-Platform Build and Release

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Icon Paths
        shell: bash
        run: |
          echo "当前工作目录: $(pwd)"
          echo "图标文件列表:"
          ls -l icons/
          
          if [ -f "icons/icon.ico" ]; then
            echo "✅ 找到 icon.ico 文件"
          else
            echo "::error::未找到 icons/icon.ico 文件！请确保图标位于 icons/ 文件夹中"
            exit 1
          fi

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src, clippy

      - name: Install Tauri CLI
        run: cargo install tauri-cli --version "^2.0.0"

      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            librsvg2-dev \
            patchelf \
            libudev-dev \
            pkg-config \
            libayatana-appindicator3-dev

      - name: Install WiX Toolset for Windows
        if: matrix.platform == 'windows-latest'
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix.zip"
          Expand-Archive -Path "wix.zip" -DestinationPath "wix"
          $wixPath = "$pwd\wix"
          echo "WIX_PATH=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "$wixPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check Windows Dependencies
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          $regPath = "HKLM:\SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"
          if (-not (Test-Path $regPath)) {
            Write-Host "WebView2 not found, installing..."
            $installerPath = "$env:TEMP\MicrosoftEdgeWebview2Setup.exe"
            Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile $installerPath
            Start-Process -FilePath $installerPath -ArgumentList "/silent /install" -Wait
          } else {
            Write-Host "WebView2 is already installed"
          }

      - name: Set Application Version
        shell: bash
        run: |
          BASE_VERSION=$(grep -E '"version":' tauri.conf.json | sed -E 's/.*"version": *"([^"]+).*/\1/')
          
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            VERSION="${BASE_VERSION}+manual.${{ github.run_id }}"
          fi

          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            FINAL_VERSION=$(echo "$VERSION" | sed -E 's/[-+].*//')
            FINAL_VERSION=$(echo "$FINAL_VERSION" | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')
            if [[ "$FINAL_VERSION" =~ ^[0-9]+\.[0-9]+$ ]]; then
              FINAL_VERSION="$FINAL_VERSION.0"
            elif [[ "$FINAL_VERSION" =~ ^[0-9]+$ ]]; then
              FINAL_VERSION="$FINAL_VERSION.0.0"
            fi
          else
            FINAL_VERSION=$VERSION
          fi

          sed -i.bak -E "s/\"version\": *\"[^\"]+\"/\"version\": \"$FINAL_VERSION\"/" tauri.conf.json && rm tauri.conf.json.bak
          sed -i.bak -E "s/^version = \"[^\"]+\"/version = \"$FINAL_VERSION\"/" Cargo.toml && rm Cargo.toml.bak
          echo "📦 Version: $FINAL_VERSION"

      - name: Build Tauri Application
        shell: bash
        run: |
          echo "构建前目录结构:"
          ls -l
          cargo tauri build --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ github.ref_name || 'manual' }}
          path: |
            target/release/bundle/**
            target/**/*.msi
            target/**/*.AppImage
            target/**/*.deb
          retention-days: 7
          if-no-files-found: error  # 改为 error 确保文件存在

      - name: Show Build Results
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            dir /s /b target\\release\\bundle || true
            dir /s /b target\\*.msi || true
          else
            find target/release/bundle -type f -print || true
            find ${{ github.workspace }} -name '*.AppImage' -o -name '*.deb' -print || true
          fi

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true  # 必须获取所有标签才能生成 changelog

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: build-*
          merge-multiple: true

      - name: Verify downloaded artifacts
        run: |
          echo "已下载的构建文件:"
          find artifacts -type f -print
          if [ -z "$(find artifacts -type f)" ]; then
            echo "::error::未找到任何构建文件!"
            exit 1
          fi

      - name: Generate Changelog
        id: generate_changelog
        run: |
          # 获取当前标签
          CURRENT_TAG="${{ github.ref_name }}"
          
          # 获取上一个标签（如果有）
          PREV_TAG=$(git describe --tags --abbrev=0 "$CURRENT_TAG^" 2>/dev/null || true)
          
          # 创建 changelog.md 文件
          echo "# Release $CURRENT_TAG" > changelog.md
          echo "" >> changelog.md
          echo "## Changelog" >> changelog.md
          echo "" >> changelog.md
          
          if [ -z "$PREV_TAG" ]; then
            # 没有上一个标签，获取所有提交
            echo "没有找到之前的标签，将显示所有提交记录" | tee -a changelog.md
            git log --pretty=format:'- %s (%h)' >> changelog.md
          else
            # 获取两个标签之间的提交
            echo "从 $PREV_TAG 到 $CURRENT_TAG 的变更:" | tee -a changelog.md
            git log --pretty=format:'- %s (%h)' "$PREV_TAG".."$CURRENT_TAG" >> changelog.md
          fi
          
          echo "" >> changelog.md
          echo "## Build Artifacts" >> changelog.md
          echo "" >> changelog.md
          
          # 添加构建文件列表
          echo "### Windows" >> changelog.md
          find artifacts -name '*.msi' -exec echo "- {}" \; | sed 's|artifacts/||' >> changelog.md
          echo "" >> changelog.md
          
          echo "### Linux" >> changelog.md
          find artifacts -name '*.AppImage' -o -name '*.deb' -exec echo "- {}" \; | sed 's|artifacts/||' >> changelog.md
          
          # 显示生成的 changelog
          echo "生成的 changelog:"
          cat changelog.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: file://changelog.md  # 直接从文件读取内容
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          # 上传 artifacts 目录中的所有文件
          for file in $(find artifacts -type f); do
            echo "📤 Uploading $file"
            filename=$(basename "$file")
            curl -sS \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type "$file")" \
              --data-binary @"$file" \
              "${{ steps.create_release.outputs.upload_url }}?name=$filename"
          done

      - name: Show Release URL
        run: echo "✅ Release created at ${{ steps.create_release.outputs.html_url }}"




