name: Tauri Cross-Platform Build and Release

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Verify Icon Paths
        shell: bash
        run: |
          echo "当前工作目录: $(pwd)"
          echo "图标文件列表:"
          ls -l icons/
          
          if [ -f "icons/icon.ico" ]; then
            echo "✅ 找到 icon.ico 文件"
          else
            echo "::error::未找到 icons/icon.ico 文件！请确保图标位于 icons/ 文件夹中"
            exit 1
          fi

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src, clippy

      - name: Install Tauri CLI
        run: cargo install tauri-cli --version "^2.0.0"

      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            librsvg2-dev \
            patchelf \
            libudev-dev \
            pkg-config \
            libayatana-appindicator3-dev

      # 💡 建议: 对于 Tauri v2, 此步骤可能不再需要。可以尝试移除。
#      - name: Install WiX Toolset for Windows
#        if: matrix.platform == 'windows-latest'
#        run: |
#          $ProgressPreference = 'SilentlyContinue'
#          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix.zip"
#          Expand-Archive -Path "wix.zip" -DestinationPath "wix"
#          $wixPath = "$pwd\wix"
#          echo "WIX_PATH=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
#          echo "$wixPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check Windows Dependencies
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          $regPath = "HKLM:\SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"
          if (-not (Test-Path $regPath)) {
            Write-Host "WebView2 not found, installing..."
            $installerPath = "$env:TEMP\MicrosoftEdgeWebview2Setup.exe"
            Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile $installerPath
            Start-Process -FilePath $installerPath -ArgumentList "/silent /install" -Wait
          } else {
            Write-Host "WebView2 is already installed"
          }

      - name: Set Application Version
        shell: bash
        run: |
          BASE_VERSION=$(grep -E '"version":' tauri.conf.json | sed -E 's/.*"version": *"([^"]+).*/\1/')
          
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            VERSION="${BASE_VERSION}+manual.${{ github.run_id }}"
          fi

          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            FINAL_VERSION=$(echo "$VERSION" | sed -E 's/[-+].*//')
            FINAL_VERSION=$(echo "$FINAL_VERSION" | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')
            if [[ "$FINAL_VERSION" =~ ^[0-9]+\.[0-9]+$ ]]; then
              FINAL_VERSION="$FINAL_VERSION.0"
            elif [[ "$FINAL_VERSION" =~ ^[0-9]+$ ]]; then
              FINAL_VERSION="$FINAL_VERSION.0.0"
            fi
          else
            FINAL_VERSION=$VERSION
          fi

          sed -i.bak -E "s/\"version\": *\"[^\"]+\"/\"version\": \"$FINAL_VERSION\"/" tauri.conf.json && rm tauri.conf.json.bak
          sed -i.bak -E "s/^version = \"[^\"]+\"/version = \"$FINAL_VERSION\"/" Cargo.toml && rm Cargo.toml.bak
          echo "📦 Version: $FINAL_VERSION"

      - name: Build Tauri Application
        shell: bash
        run: |
          echo "构建前目录结构:"
          ls -lR third-party # 添加这行来调试，确认子模块内容已拉取
          cargo tauri build --verbose
          # 仅针对 Windows 平台重命名安装包
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            # 查找所有 MSI 文件
            find target/release/bundle/msi -name '*.msi' -print0 | while IFS= read -r -d '' file; do
              # 获取文件名和目录
              dir=$(dirname "$file")
              filename=$(basename "$file")
          
              # 移除语言标记 (如 _en-US)
              new_name=$(echo "$filename" | sed -E 's/_en-US//g')
          
              # 重命名文件
              mv "$file" "$dir/$new_name"
              echo "✅ 重命名: $filename -> $new_name"
            done
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ github.ref_name || 'manual' }}
          path: |
            target/**/*.msi
            target/**/*.AppImage
            target/**/*.deb
          retention-days: 7
          if-no-files-found: error

      - name: Show Build Results
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            dir /s /b target\\release\\bundle || true
            dir /s /b target\\*.msi || true
          else
            find target/release/bundle -type f -print || true
            find ${{ github.workspace }} -name '*.AppImage' -o -name '*.deb' -print || true
          fi

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Checkout code with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: build-*
          merge-multiple: true

      - name: Prepare Clean Release Artifacts
        run: |
          mkdir -p release_files
          find artifacts -type f \( -name '*.msi' -o -name '*.AppImage' -o -name '*.deb' \) -exec cp {} release_files/ \;
          echo "准备上传的文件:"
          ls -lh release_files/

      - name: Generate Changelog
        run: |
          CURRENT_TAG="${{ github.ref_name }}"
          PREV_TAG=$(git describe --tags --abbrev=0 "$CURRENT_TAG^" 2>/dev/null || true)
          
          echo "# Release $CURRENT_TAG" > changelog.md
          echo "" >> changelog.md
          echo "## Changelog" >> changelog.md
          echo "" >> changelog.md
          
          if [ -z "$PREV_TAG" ]; then
            git log --oneline --no-decorate >> changelog.md
          else
            git log --oneline --no-decorate "$PREV_TAG".."$CURRENT_TAG" >> changelog.md
          fi
          
          echo "" >> changelog.md
          echo "## Downloads" >> changelog.md
          echo "" >> changelog.md
          ls release_files/ | while read file; do echo "- \`$file\`"; done >> changelog.md
          
          cat changelog.md

      - name: Create Release with Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: changelog.md
          files: release_files/*
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Release URL
        run: echo "✅ Release created at https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
